Repository shibam-naskar/IMAGE_COMPRESOR, pull requests merged in 2022-02, with the labels that each got.

#9 footer
  css/style.css
  index.html
Labels: enhancement, medium, JWOC

#12 Added A Nav Bar
  css/style.css
  index.html
Labels: easy, JWOC

#14 Card added for Compression Details using Bootstrap
  css/style.css
  index.html
  js/main.js
Labels: medium, JWOC

#22 Updated README.md file.
  README.md
  assets/homepage.png
Labels: easy, JWOC

#23 Fix drag and drop file upload feature
  js/main.js
Labels: enhancement, JWOC, hard

#25 Update README.md
  README.md
  assets/homepage.png
  assets/img/demo.png
Labels: documentation, enhancement, medium, JWOC

#30 Enhanced Over all styling
  assets/img/.picasa.ini
  assets/img/.picasaoriginals/.picasa.ini
  assets/img/.picasaoriginals/background.jpg
  assets/img/background.jpg
  css/style.css
  index.html
Labels: enhancement, medium, JWOC
